### ISSUE TITLE
About to the import Errors and something

### ISSUE THREAD

**Issue by zoneyaner** [erenming/blog#9]
as it to say,which means i can't correctly import some module:
There are two : 

-  ImportError: cannot import name 'Celery'

- execute_from_command_line(sys.argv) catch an Exception 

i have known the database you deploy is good,can i replace it to use mysql and so on(i do learn some database except yours,sad face!), and how i do next to config.

**Comment by tomming233** [comment]
first error: please run ```pip install -r requirements/dev.txt```
second error: please ensure mysql install and database config in settings.py is correct,

or you can refer to https://github.com/tomming233/blog#记录于2017-10-07, and try again

**Comment by zhong-yan** [comment]
well i got the idea and have a good done with the project in my PC,thanks!
the question what i cause because i am new to Django and now i get the help of Django Docs and yours,tx again!.
